### ISSUE TITLE
Windows Defender flags as "Zpevdo.B"

### ISSUE THREAD

**Issue by LiNCHx** [beat-saber-modding-group/BeatSaberModInstaller#37] opened 2019-04-16 16:12 UTC
Windows Defender just flagged this File as "Tojan:Win32/Zpevdo.B".

> Warning level: Heavy
> Status: In Quarantine
> Category: Tojan
> Details: This Program is dangerous. It executes commands of an attacker.

![av](https://user-images.githubusercontent.com/34384416/56226273-2f257400-6073-11e9-8ab0-b6af31a13c7c.PNG)

**Comment by 0ttovonBismarck** [comment] 2019-04-16 16:30
I have the same problem, so I deleted the file and now, when i try to download it again, windows blocks that, too.

**Comment by Assistant** [comment] 2019-04-16 17:24
Duplicate of #20

**Closed by Assistant** 2019-04-16 17:24 UTC
